[package]
name = "testcrate"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
futures-await = { path = ".." }

[dev-dependencies]
compiletest_rs = "0.2"

[[test]]
name = "compiletest"
harness = false
