[package]
name = "futures-channel"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/futures-rs"
homepage = "https://github.com/alexcrichton/futures-rs"
documentation = "https://docs.rs/futures-core"
description = """
Channels for asynchronous communication using futures-rs.
"""

[features]
std = []
default = ["std"]

[dependencies.futures-core]
version = "0.1.0"
path = "../futures-core"
default-features = false
features = ["std"]

[dev-dependencies]
futures = { path = "../futures", version = "0.2" }
futures-executor = { path = "../futures-executor", version = "0.1" }
