language: rust

# Most tests run nightly for now due to the usage of Cargo workspaces, Cargo
# overrides, and some performance improvements in the compiler.
rust:
  - nightly

# We should not, however, break the build on other channels!
matrix:
  include:
    - os: linux
      rust: stable
      script: cargo build --manifest-path futures-minihttp/Cargo.toml
    - os: osx
      rust: stable
      script: cargo build --manifest-path futures-minihttp/Cargo.toml
    - os: linux
      rust: beta
      script: cargo build --manifest-path futures-minihttp/Cargo.toml
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo test
  - cargo test --manifest-path futures-io/Cargo.toml
  - cargo test --manifest-path futures-iobuf/Cargo.toml
  - cargo test --manifest-path futures-cpupool/Cargo.toml
  - cargo test --manifest-path futures-mio/Cargo.toml
  - cargo test --manifest-path futures-tls/Cargo.toml
  - cargo test --manifest-path futures-tls/Cargo.toml --features force-openssl
  - cargo test --manifest-path futures-minihttp/Cargo.toml
  - cargo test --manifest-path futures-minihttp/tls-example/Cargo.toml

  - cargo doc --no-deps
  - cargo doc --no-deps --manifest-path futures-io/Cargo.toml
  - cargo doc --no-deps --manifest-path futures-iobuf/Cargo.toml
  - cargo doc --no-deps --manifest-path futures-cpupool/Cargo.toml
  - cargo doc --no-deps --manifest-path futures-mio/Cargo.toml
  - cargo doc --no-deps --manifest-path futures-tls/Cargo.toml
after_success:
  - travis-cargo --only nightly doc-upload
  - travis-cargo coveralls --no-sudo
env:
  global:
    secure: LVrtwDI0IJradnHRk53dGWtTS+limhkuHym17wuto/Zaz6IJB9aq7G5wSYuZU3qabcxah7pigjXPFgzYwFD6mNHW1DAuAko1qOi4AL0rvg+rA7Fa5E9NEIxoqzCf+wBtqCvomBe/akOs7UtHdjE3CZpIEPwSHVf3jf61suB0mPVUW0AFTHvYTvHT4lyHjlruY+Ifi350yb4t0Oy9rU1bHNtX0q1T0mKuTnKkmpCT2Kj+2L7afgsAR3UgBjL3Py89LXmnF5VxSMGJWa6HL3xgEi3CXxBRQFdr+vipIDejWtjY+7DzvSRHid1rVfwCLdLfTwvA3Pf3b0I5DSJnjzRgKkfiH2j7JNFtCvLz+mM5C/4QJzAgNmdyNuDv0qOy07OABtYs/LE60f6ZZ5YMZAloMtA/9qQjJx+c2jO2nTZkx6vNJ5C421yzm2klQSL0d8pFaDmojqC5pT85MYhf3mESqSw1UjwFPa0xFtysT52oJBcyvwI/wBYbK40sArjSDZaU2Jncw9ptDWML/xUM+sWHF7ZW/mI1V15lqaCBX91xlbppfWDMgNF2c60vC90t0entbGpYLvHjQMdW6iucbsLLN5KAPzYPuufX2vJa8V1gxMxZ7CLcVLx9lmm3uEdrOZLEg4Fg7H7Xqc2JRygbNrTtOeBw1/o73znnnjEv8Vl3xqg=
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
