[package]
name = "futures-await"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.11", features = ["full", "parsing"], default-features = false }
quote = "0.3"
