[package]
name = "futures"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[workspace]
members = ["ssl", "mio", "http", "tokio", "http/ssl-example"]

[dependencies]
log = "0.3"

[dev-dependencies]
support = { path = "tests/support" }

[replace."openssl:0.7.14"]
git = "https://github.com/alexcrichton/rust-openssl"
branch = "mid-handshake"
