[package]
name = "futures-await"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[workspace]

[dependencies]
futures-await-macros = { path = "futures-await-macros" }
futures = "0.1"
