[package]
name = "futures-io"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexcrichton/futures-rs"
homepage = "https://github.com/alexcrichton/futures-rs"
documentation = "http://alexcrichton.com/futures-rs/futures_io/"
description = """
An I/O abstraction layer built on top of streams of readiness. Includes many
std::io primitives intended for usage with futures.
"""

[dependencies]
futures = { path = "..", version = "0.1.0" }
log = "0.3"
