[package]
name = "futures-util"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/futures-rs"
homepage = "https://github.com/alexcrichton/futures-rs"
documentation = "https://docs.rs/futures-core"
description = """
Common utilities and extension traits for the futures-rs library.
"""

[features]
std = ["bytes", "log", "futures-core/std", "futures-io/std", "futures-sink/std"]
default = ["std"]

[dependencies]
bytes = { version = "0.4", optional = true }
log = { version = "0.4", optional = true }
futures-core = { path = "../futures-core", version = "0.2.0", default-features = false }
futures-channel = { path = "../futures-channel", version = "0.2.0", default-features = false }
futures-io = { path = "../futures-io", version = "0.2.0", default-features = false }
futures-sink = { path = "../futures-sink", version = "0.2.0", default-features = false}

[dev-dependencies]
futures = { path = "../futures", version = "0.2" }
futures-executor = { path = "../futures-executor", version = "0.2" }
futures-channel = { path = "../futures-channel", version = "0.2" }
