[package]
name = "futures-util"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/futures-rs"
homepage = "https://github.com/alexcrichton/futures-rs"
documentation = "https://docs.rs/futures-core"
description = """
Common utilities and extension traits for the futures-rs library.
"""

[features]
std = ["futures-core/std", "futures-sink/std"]
default = ["std"]

[dependencies]
futures-core = { path = "../futures-core", version = "0.1.0" }
futures-channel = { path = "../futures-channel", version = "0.1.0" }
futures-sink = { path = "../futures-sink", version = "0.1.0" }
