[package]
name = "ssl"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
# http = { path = "../http" }
futures = { path = ".." }
openssl = "0.7"

[dev-dependencies]
futuremio = { path = "../mio" }
env_logger = "0.3"
