[package]
name = "techempower1"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
env_logger = "0.3"
futures = { path = "../.." }
futures-minihttp = { path = ".." }
rustc-serialize = "0.3"
time = "0.1"
