[package]
name = "techempower2"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
env_logger = "0.3"
futures = { path = "../.." }
futures-minihttp = { path = ".." }
futures-cpupool = { path = "../../futures-cpupool" }
postgres = "0.11"
r2d2 = "0.7"
r2d2_postgres = "0.10"
rustc-serialize = "0.3"
rand = "0.3"
